package org.qrdlife.wikiconnect.wikimonitor.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.qrdlife.wikiconnect.wikimonitor.model.User;
import org.qrdlife.wikiconnect.wikimonitor.repository.UserRepository;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class UserServiceOAuthTest {

    @Mock
    private UserRepository userRepository;

    @Mock
    private SettingsService settingsService;

    private UserService userService;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        userService = new UserService(userRepository, settingsService);
    }

    @Test
    void findOrCreateUser_ExistingUser_UpdatesUsername() {
        Long centralId = 12345L;
        String oldName = "OldName";
        String newName = "NewName";

        User existingUser = new User(centralId, oldName);

        when(userRepository.findByCentralId(centralId)).thenReturn(Optional.of(existingUser));
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

        User result = userService.findOrCreateUser(centralId, newName);

        assertNotNull(result);
        assertEquals(newName, result.getUsername());
        assertEquals(centralId, result.getCentralId()); // Assuming User has getCentralId() generated by @Data
        verify(userRepository).save(existingUser);
    }

    @Test
    void findOrCreateUser_NewUser_CreatesUser() {
        Long centralId = 67890L;
        String name = "NewUser";

        when(userRepository.findByCentralId(centralId)).thenReturn(Optional.empty());
        when(userRepository.count()).thenReturn(1L); // Not first user
        when(settingsService.isAutoApproveEnabled()).thenReturn(false);
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

        User result = userService.findOrCreateUser(centralId, name);

        assertNotNull(result);
        assertEquals(name, result.getUsername());
        assertEquals(centralId, result.getCentralId());
        verify(userRepository).save(any(User.class));
    }
}
